xcopy %~dp0\thirdparty\easy_profiler\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\libsofa\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\openvr\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\ovraudio\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\steamaudio\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\fmod\bin\*.dll %~dp0\build\ProfilingApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\easy_profiler\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\libsofa\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\openvr\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\ovraudio\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\steamaudio\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\fmod\bin\*.dll %~dp0\build\ProfilingApp\bin\Debug\. /y /i