xcopy %~dp0\thirdparty\easy_profiler\bin\*.dll %~dp0\build\ExperimentApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\libsofa\bin\*.dll %~dp0\build\ExperimentApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\openvr\bin\*.dll %~dp0\build\ExperimentApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\sdl\bin\*.dll %~dp0\build\ExperimentApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\fmod\bin\*.dll %~dp0\build\ExperimentApp\bin\Release\. /y /i
xcopy %~dp0\thirdparty\easy_profiler\bin\*.dll %~dp0\build\ExperimentApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\libsofa\bin\*.dll %~dp0\build\ExperimentApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\openvr\bin\*.dll %~dp0\build\ExperimentApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\sdl\bin\*.dll %~dp0\build\ExperimentApp\bin\Debug\. /y /i
xcopy %~dp0\thirdparty\fmod\bin\*.dll %~dp0\build\ExperimentApp\bin\Debug\. /y /i